### PR TITLE
Update for 0.6.0

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
@pmlandwehr Are you still maintaining this feedstock? If not, I'm happy to take over here. Either way, can you add me as a recipe maintainer?

**Comment by cpcloud** [comment]
ping @pmlandwehr

**Comment by cpcloud** [comment]
ping @pmlandwehr 

Is there any chance you can get to this in the next day or two?

If you're strapped for time, can you add me to the maintainers list so that I can commit to the repo?

This is blocking me on a few things right now.

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
@cpcloud Thanks so much for working on this pull! Any help you can give with maintaining the feedstock would definitely be welcome!

**Pull request merged**
